/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilas;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author mp6-9
 */
public class Dashboard extends javax.swing.JFrame {

    public Stack SProfesores = new Stack();
    public Stack SAsignatura = new Stack();
    ProfesorView pv = new ProfesorView();
    AsignaturaView av = new AsignaturaView();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        btnGuardarA.setVisible(false);
        btnGuardarP.setVisible(false);
    }

    public boolean verificarCedula(String cedula) {
        return cedula.length() < 6 || cedula.length() > 10;
    }

    public boolean verificarCodigoAsignatura(String code) {
        return code.length() < 5 || code.length() > 9;
    }

    public boolean verificarProfesor(String cedula, String nombres, String apellidos,
            String asignatura) {
        return (verificarCedula(cedula)
                || "Seleccione".equalsIgnoreCase(nombres)
                || "Seleccione".equalsIgnoreCase(apellidos)
                || "Seleccione".equalsIgnoreCase(asignatura));
    }

    public void mostrarProfesores() {
        Node aux = SProfesores.getTope();
        String msj = "";
        //Cargar las asignaturas en el combobox
        if (!SProfesores.isEmpty()) {
            while (aux != null) {
                Profesor p = (Profesor) aux.getDato();
                msj += p.getNombres() + " - " + p.getAsignatura() + "\n";
                aux = aux.getNext();
            }
            JOptionPane.showMessageDialog(null, msj);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Profesores ingresados");
        }
    }

    public boolean verificarAsignatura(String codigo, String numeroGrupo, String nombre,
            String duracion, String creditos) {
        return (verificarCodigoAsignatura(codigo)
                || "Seleccione".equalsIgnoreCase(numeroGrupo)
                || "".equalsIgnoreCase(nombre)
                || "Seleccione".equalsIgnoreCase(duracion)
                || "Seleccione".equalsIgnoreCase(creditos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnGuardarA = new javax.swing.JButton();
        btnGuardarP = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbNAsignaturas = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jButton1.setText("Gestionar Asignatura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gestiona Profesores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnGuardarA.setText("Guardar Asignatura");
        btnGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAActionPerformed(evt);
            }
        });

        btnGuardarP.setText("Guardar Profesor");
        btnGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPActionPerformed(evt);
            }
        });

        jButton3.setText("Ver profesores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbNAsignaturas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cbNAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNAsignaturasActionPerformed(evt);
            }
        });

        jButton4.setText("Porcentaje");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardarA)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbNAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarP)
                    .addComponent(btnGuardarA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(cbNAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        av.setSize(300, 300);
        panelPrincipal.removeAll();
        panelPrincipal.add(av, BorderLayout.CENTER);
        av.setVisible(true);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        btnGuardarA.setVisible(true);
        btnGuardarP.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pv.setSize(300, 300);
        panelPrincipal.removeAll();
        panelPrincipal.add(pv, BorderLayout.CENTER);
        pv.setVisible(true);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        btnGuardarA.setVisible(false);
        btnGuardarP.setVisible(true);
        Node aux = SAsignatura.getTope();
        Node aux2 = SAsignatura.getTope();
        //Cargar las asignaturas en el combobox
        if (!SAsignatura.isEmpty()) {
            while (aux != null) {
                Asignatura a = (Asignatura) aux.getDato();
                pv.cbAsignatura.addItem(a.getNombre());
                aux = aux.getNext();
            }
        }

        //Cargar las asignaturas en el combobox de abajo
        if (!SAsignatura.isEmpty()) {
            while (aux2 != null) {
                Asignatura a = (Asignatura) aux2.getDato();
                cbNAsignaturas.addItem(a.getNombre());
                aux2 = aux2.getNext();
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPActionPerformed
        //Guargar Profesor
        String cedula = pv.txtCedula.getText();
        String nombres = pv.txtNombres.getText();
        String apellidos = pv.txtApellidos.getText();
        String asignatura = pv.cbAsignatura.getSelectedItem().toString();

        if (verificarProfesor(cedula, nombres, apellidos, asignatura)) {
            JOptionPane.showMessageDialog(null, "Datos erroneos, revise los requerimientos");
        } else {
            Profesor p = new Profesor(cedula, nombres, apellidos, asignatura);
            SProfesores.push(p);
            JOptionPane.showMessageDialog(null, "Insertado en la pila con éxito");
        }
    }//GEN-LAST:event_btnGuardarPActionPerformed

    private void btnGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAActionPerformed
        //Guargar Asignatura
        String codigo = av.txtCodigo.getText();
        String nombre = av.txtNombre.getText();
        String numeroGrupo = av.cbGrupo.getSelectedItem().toString();
        String duracion = av.cbDuracion.getSelectedItem().toString();
        String cantidadCreditos = av.cbCreditos.getSelectedItem().toString();

        if (verificarAsignatura(codigo, numeroGrupo, nombre, duracion, cantidadCreditos)) {
            JOptionPane.showMessageDialog(null, "Datos erroneos, revise los requerimientos");
        } else {
            Asignatura a = new Asignatura(codigo, numeroGrupo, nombre, duracion, cantidadCreditos);
            SAsignatura.push(a);
            JOptionPane.showMessageDialog(null, "Insertada en la pila con éxito");
        }
    }//GEN-LAST:event_btnGuardarAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mostrarProfesores();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbNAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNAsignaturasActionPerformed

    }//GEN-LAST:event_cbNAsignaturasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Node aux = SProfesores.getTope();
        String eleccion = cbNAsignaturas.getSelectedItem().toString();
        int cantidadProfesores = 0, cantidadAsignatura = 0;

        if (eleccion.equalsIgnoreCase("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Debe elegir una asignatura");
        } else if (!SProfesores.isEmpty()) {
            while (aux != null) {
                Profesor p = (Profesor) aux.getDato();
                if (p.getAsignatura().equalsIgnoreCase(eleccion)) {
                    cantidadAsignatura++;
                }
                cantidadProfesores++;
                aux = aux.getNext();
            }

            JOptionPane.showMessageDialog(null, "El porcentaje de profesores que dictan "
                    + eleccion + " es del " + (cantidadAsignatura * 100 / cantidadProfesores) + "%");

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un profesor");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarA;
    private javax.swing.JButton btnGuardarP;
    private javax.swing.JComboBox cbNAsignaturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
